### PR TITLE
final-fixes

### PR DESCRIPTION
**Pull request by Vijay-Malke**

### CODE REVIEW

**Comment by nivnar** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/OfficeDocs-SkypeforBusiness-Test-pr.pt-br, working directory: W:\5mjt-s, target branch: master, target branch commit: ac23b9185cffc79ea3112e6219feb253c371a765, source branch: 9424b64b5e296507e1ed90a566cc4a2b/final-fixes, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C730e0d29-50de-96c3-2fec-90d1d64e501c%5CPullRequest%5C201808240554338379-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=HsqK4LtOXfuEgPTEkZP5ATEQ8ZHesKtyoAyp020p6y4%3D&st=2018-08-24T05%3A49%3A50Z&se=2018-09-24T05%3A54%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/OfficeDocs-SkypeforBusiness-Test-pr.pt-br, working directory: W:\lnsk-s, target branch: master, target branch commit: ac23b9185cffc79ea3112e6219feb253c371a765, source branch: 9424b64b5e296507e1ed90a566cc4a2b/final-fixes, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C730e0d29-50de-96c3-2fec-90d1d64e501c%5CPullRequest%5C201808240706414575-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=W4U3D6ANMgKNHPKVHzuvyrfssM62%2Bj1geYuBWEcinsQ%3D&st=2018-08-24T07%3A01%3A58Z&se=2018-09-24T07%3A06%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/deploying-a-sql-server-nonstandard-port-and-alias-in-lync-server-2013.md](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/deploying-a-sql-server-nonstandard-port-and-alias-in-lync-server-2013.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-assigning-a-server-to-server-authentication-certificate-to-lync-server-2013.md](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/lync-server-2013-assigning-a-server-to-server-authentication-certificate-to-lync-server-2013.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-choosing-a-topology.md](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/lync-server-2013-choosing-a-topology.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-configure-a-trunk-without-media-bypass.md](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/lync-server-2013-configure-a-trunk-without-media-bypass.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-configure-certificates-for-servers.md](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/lync-server-2013-configure-certificates-for-servers.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-configure-web-publishing-rules-for-a-single-internal-pool.md](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/lync-server-2013-configure-web-publishing-rules-for-a-single-internal-pool.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-create-a-voice-routing-test-case.md](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/lync-server-2013-create-a-voice-routing-test-case.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-deploying-lync-server-2013-standard-edition-into-an-existing-lync-server-2013-enterprise.md](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/lync-server-2013-deploying-lync-server-2013-standard-edition-into-an-existing-lync-server-2013-enterprise.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-iis-requirements-for-front-end-pools-and-standard-edition-servers.md](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/lync-server-2013-iis-requirements-for-front-end-pools-and-standard-edition-servers.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-installing-lync-for-iphone-and-ipad.md](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/lync-server-2013-installing-lync-for-iphone-and-ipad.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-port-summary-reverse-proxy.md](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/lync-server-2013-port-summary-reverse-proxy.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-request-and-configure-a-certificate-for-your-reverse-http-proxy.md](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/lync-server-2013-request-and-configure-a-certificate-for-your-reverse-http-proxy.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-setting-up-lync-federation.md](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/lync-server-2013-setting-up-lync-federation.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-test-voice-routing.md](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/lync-server-2013-test-voice-routing.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-using-lync-connectivity-analyzer.md](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/lync-server-2013-using-lync-connectivity-analyzer.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-using-lync-skype-connectivity-as-an-end-user.md](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/lync-server-2013-using-lync-skype-connectivity-as-an-end-user.md) | :white_check_mark:Succeeded | |
[server-2013/migrate-response-groups.md](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/migrate-response-groups.md) | :white_check_mark:Succeeded | |
[server-2013/migrate-response-groups_1.md](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/migrate-response-groups_1.md) | :white_check_mark:Succeeded | |
[server-2013/phase-10-decommission-legacy-site.md](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/phase-10-decommission-legacy-site.md) | :white_check_mark:Succeeded | |
[server-2013/toc.yml](https://github.com/Vijay-Malke/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/final-fixes/server-2013/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C730e0d29-50de-96c3-2fec-90d1d64e501c%5CPullRequest%5C201808240728070481-23%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=eISrmef6hEcB%2BTg4YZuZHU10bvPkhPkjnLQm3ucFLnY%3D&st=2018-08-24T07%3A25%3A25Z&se=2018-09-24T07%3A30%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by DanMSFT** [comment]
Closing per Hemant, so that a modification can be made then resubmitted.

**Pull request closed without merging**
