### PR TITLE
Asteriks & alert issue fixed

### PR DESCRIPTION
**Pull request by v-hearya**

### CODE REVIEW

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/deploying-a-sql-server-nonstandard-port-and-alias-in-lync-server-2013.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/deploying-a-sql-server-nonstandard-port-and-alias-in-lync-server-2013.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-assigning-a-server-to-server-authentication-certificate-to-lync-server-2013.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-assigning-a-server-to-server-authentication-certificate-to-lync-server-2013.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-choosing-a-topology.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-choosing-a-topology.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-configure-a-trunk-without-media-bypass.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-configure-a-trunk-without-media-bypass.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-configure-certificates-for-servers.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-configure-certificates-for-servers.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-configure-web-publishing-rules-for-a-single-internal-pool.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-configure-web-publishing-rules-for-a-single-internal-pool.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-create-a-voice-routing-test-case.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-create-a-voice-routing-test-case.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-deploying-lync-server-2013-standard-edition-into-an-existing-lync-server-2013-enterprise.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-deploying-lync-server-2013-standard-edition-into-an-existing-lync-server-2013-enterprise.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-iis-requirements-for-front-end-pools-and-standard-edition-servers.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-iis-requirements-for-front-end-pools-and-standard-edition-servers.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-installing-lync-for-iphone-and-ipad.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-installing-lync-for-iphone-and-ipad.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-port-summary-reverse-proxy.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-port-summary-reverse-proxy.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-request-and-configure-a-certificate-for-your-reverse-http-proxy.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-request-and-configure-a-certificate-for-your-reverse-http-proxy.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-setting-up-lync-federation.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-setting-up-lync-federation.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-test-voice-routing.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-test-voice-routing.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-using-lync-connectivity-analyzer.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-using-lync-connectivity-analyzer.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-using-lync-skype-connectivity-as-an-end-user.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-using-lync-skype-connectivity-as-an-end-user.md) | :white_check_mark:Succeeded | |
[server-2013/migrate-response-groups.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/migrate-response-groups.md) | :white_check_mark:Succeeded | |
[server-2013/migrate-response-groups_1.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/migrate-response-groups_1.md) | :white_check_mark:Succeeded | |
[server-2013/phase-10-decommission-legacy-site.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/phase-10-decommission-legacy-site.md) | :white_check_mark:Succeeded | |
[server-2013yes](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013yes) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C730e0d29-50de-96c3-2fec-90d1d64e501c%5CPullRequest%5C201808242121164001-24%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=34o%2FunFUB9mi0nWPNM1JTm2Tk2cec9xY6Q7d6fQoDzs%3D&st=2018-08-24T21%3A18%3A38Z&se=2018-09-24T21%3A23%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/deploying-a-sql-server-nonstandard-port-and-alias-in-lync-server-2013.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/deploying-a-sql-server-nonstandard-port-and-alias-in-lync-server-2013.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-assigning-a-server-to-server-authentication-certificate-to-lync-server-2013.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-assigning-a-server-to-server-authentication-certificate-to-lync-server-2013.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-choosing-a-topology.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-choosing-a-topology.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-configure-a-trunk-without-media-bypass.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-configure-a-trunk-without-media-bypass.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-configure-certificates-for-servers.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-configure-certificates-for-servers.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-configure-web-publishing-rules-for-a-single-internal-pool.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-configure-web-publishing-rules-for-a-single-internal-pool.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-create-a-voice-routing-test-case.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-create-a-voice-routing-test-case.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-deploying-lync-server-2013-standard-edition-into-an-existing-lync-server-2013-enterprise.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-deploying-lync-server-2013-standard-edition-into-an-existing-lync-server-2013-enterprise.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-iis-requirements-for-front-end-pools-and-standard-edition-servers.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-iis-requirements-for-front-end-pools-and-standard-edition-servers.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-installing-lync-for-iphone-and-ipad.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-installing-lync-for-iphone-and-ipad.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-port-summary-reverse-proxy.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-port-summary-reverse-proxy.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-request-and-configure-a-certificate-for-your-reverse-http-proxy.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-request-and-configure-a-certificate-for-your-reverse-http-proxy.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-setting-up-lync-federation.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-setting-up-lync-federation.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-test-voice-routing.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-test-voice-routing.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-using-lync-connectivity-analyzer.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-using-lync-connectivity-analyzer.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-using-lync-skype-connectivity-as-an-end-user.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-using-lync-skype-connectivity-as-an-end-user.md) | :white_check_mark:Succeeded | |
[server-2013/migrate-response-groups.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/migrate-response-groups.md) | :white_check_mark:Succeeded | |
[server-2013/migrate-response-groups_1.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/migrate-response-groups_1.md) | :white_check_mark:Succeeded | |
[server-2013/phase-10-decommission-legacy-site.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/phase-10-decommission-legacy-site.md) | :white_check_mark:Succeeded | |
[server-2013yes](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013yes) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C730e0d29-50de-96c3-2fec-90d1d64e501c%5CPullRequest%5C201808242217094343-24%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=t5t4M92jDVJQhizegAMK5ZtBKugv7NfLzDC6HyJRP8o%3D&st=2018-08-24T22%3A14%3A12Z&se=2018-09-24T22%3A19%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nivnar** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/deploying-a-sql-server-nonstandard-port-and-alias-in-lync-server-2013.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/deploying-a-sql-server-nonstandard-port-and-alias-in-lync-server-2013.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-assigning-a-server-to-server-authentication-certificate-to-lync-server-2013.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-assigning-a-server-to-server-authentication-certificate-to-lync-server-2013.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-choosing-a-topology.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-choosing-a-topology.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-configure-a-trunk-without-media-bypass.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-configure-a-trunk-without-media-bypass.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-configure-certificates-for-servers.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-configure-certificates-for-servers.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-configure-lync-server-2013-to-work-with-unified-messaging-on-microsoft-exchange-server.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-configure-web-publishing-rules-for-a-single-internal-pool.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-configure-web-publishing-rules-for-a-single-internal-pool.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-create-a-voice-routing-test-case.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-create-a-voice-routing-test-case.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-deploying-lync-server-2013-standard-edition-into-an-existing-lync-server-2013-enterprise.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-deploying-lync-server-2013-standard-edition-into-an-existing-lync-server-2013-enterprise.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-iis-requirements-for-front-end-pools-and-standard-edition-servers.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-iis-requirements-for-front-end-pools-and-standard-edition-servers.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-installing-lync-for-iphone-and-ipad.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-installing-lync-for-iphone-and-ipad.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-port-summary-reverse-proxy.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-port-summary-reverse-proxy.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-request-and-configure-a-certificate-for-your-reverse-http-proxy.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-request-and-configure-a-certificate-for-your-reverse-http-proxy.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-response-group-disaster-recovery-procedures.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-setting-up-lync-federation.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-setting-up-lync-federation.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-test-voice-routing.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-test-voice-routing.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-using-lync-connectivity-analyzer.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-using-lync-connectivity-analyzer.md) | :white_check_mark:Succeeded | |
[server-2013/lync-server-2013-using-lync-skype-connectivity-as-an-end-user.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/lync-server-2013-using-lync-skype-connectivity-as-an-end-user.md) | :white_check_mark:Succeeded | |
[server-2013/migrate-response-groups.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/migrate-response-groups.md) | :white_check_mark:Succeeded | |
[server-2013/migrate-response-groups_1.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/migrate-response-groups_1.md) | :white_check_mark:Succeeded | |
[server-2013/phase-10-decommission-legacy-site.md](https://github.com/v-hearya/OfficeDocs-SkypeforBusiness-Test-pr.pt-br/blob/master/server-2013/phase-10-decommission-legacy-site.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C24%5C730e0d29-50de-96c3-2fec-90d1d64e501c%5CPullRequest%5C201808242224036741-24%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=m5Zo56cXy6d8TZAUNUxVf%2FAfTZJ6cPMaPUMvz0a5Bt8%3D&st=2018-08-24T22%3A21%3A42Z&se=2018-09-24T22%3A26%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Review by DanMSFT — APPROVED** [review]

**Comment by DanMSFT** [comment]
Merged but tentatiely due to a single page with an extra space thatmight cause a split Alert.

**Pull request merged**
